CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE empresa (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    razao_social VARCHAR(150) NOT NULL,
    nome VARCHAR(150) NOT NULL,

    cnpj VARCHAR(14) NOT NULL UNIQUE,

    email VARCHAR(150),
    telefone VARCHAR(20),

    ativo BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);