spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/rhflow
spring.datasource.username=postgres
spring.datasource.password=769512Kk.

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false


# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration


# Server
server.port=8080